# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
    todoItemRepository:
        class: AppBundle\Entity\DoctrineTodoItemRepository
        factory_service: "doctrine.orm.default_entity_manager"
        factory_method: getRepository
        arguments:
            - AppBundle\Entity\TodoItem


    # controllers
#    todoListController:
#        class: AppBundle\Controller\TodoListController
#        arguments:
#            - "@todoItemRepository"

#    service_name:
#        class: AppBundle\Directory\ClassName
#        arguments: ["@another_service_name", "plain_value", "%parameter_name%"]
